<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/myHearDe/VeilBrowser</PackageProjectUrl>
    <RepositoryUrl>https://github.com/myHearDe/VeilBrowser.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright (C) 2026 myHearDe</Copyright>
  </PropertyGroup>
</Project>
